CREATE OR REPLACE VIEW v_order_header AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    STATUS,
    CUSTOMER_ID,
    ITEM_COUNT,
    TOTAL_AMOUNT,
    DISCOUNT,
    CREATE_DATE AS ORDER_CREATE_DATE,
    CREATE_USER AS ORDER_CREATE_USER,
    COUPON_CODE
FROM
    ORDER_BASE.ORDER_HEADER;

CREATE OR REPLACE VIEW v_customer AS
SELECT
    CUSTOMER_ID,
    ADDRESS,
    PHONE_NO,
    STATUS AS CUSTOMER_STATUS,
    CATEGORY AS CUSTOMER_CATEGORY,
    TOTAL_ORDERS,
    TOTAL_INVOICE_AMOUNT,
    LOYALTY_POINTS,
    CREATE_DATE AS CUSTOMER_CREATE_DATE,
    CREATE_USER AS CUSTOMER_CREATE_USER
FROM
    ORDER_BASE.CUSTOMER;

CREATE OR REPLACE VIEW v_order_detail AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    ITEM_ID,
    QTY,
    TOTAL_AMOUNT,
    CREATE_DATE AS DETAIL_CREATE_DATE,
    CREATE_USER AS DETAIL_CREATE_USER
FROM
    ORDER_BASE.ORDER_DETAIL;

CREATE OR REPLACE VIEW v_promotion AS
SELECT
    PROMOTION_ID,
    CUSTOMER_CATEGORY,
    PROMOTION_TYPE,
    PROMOTION_VALUE,
    COMMENT AS PROMOTION_COMMENT
FROM
    ORDER_BASE.PROMOTION;

CREATE OR REPLACE VIEW v_invoice AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    INVOICE_DATE,
    TAX_AMOUNT,
    TOTAL_AMOUNT,
    TOTAL_ORDERS,
    DISCOUNT,
    FINAL_INVOICE_AMT,
    CREATE_DATE AS INVOICE_CREATE_DATE,
    CREATE_USER AS INVOICE_CREATE_USER
FROM
    INVOICE;
